#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fcgi
Version  : 2.4.0
Release  : 10
URL      : https://fossies.org/linux/www/old/fcgi-2.4.0.tar.gz
Source0  : https://fossies.org/linux/www/old/fcgi-2.4.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : OML
Requires: fcgi-bin = %{version}-%{release}
Requires: fcgi-lib = %{version}-%{release}
Requires: fcgi-license = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : buildreq-cpan
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
Patch1: fcgi-2.4.0-Makefile.am-CPPFLAGS.patch
Patch2: fcgi-2.4.0-configure.in.patch
Patch3: gcc44-fix-include.patch
Patch4: cve-2012-6687.patch

%description
------------------------------
See the file "LICENSE.TERMS" for information on usage and redistribution
of this file, and for a DISCLAIMER OF ALL WARRANTIES.

%package bin
Summary: bin components for the fcgi package.
Group: Binaries
Requires: fcgi-license = %{version}-%{release}

%description bin
bin components for the fcgi package.


%package dev
Summary: dev components for the fcgi package.
Group: Development
Requires: fcgi-lib = %{version}-%{release}
Requires: fcgi-bin = %{version}-%{release}
Provides: fcgi-devel = %{version}-%{release}
Requires: fcgi = %{version}-%{release}

%description dev
dev components for the fcgi package.


%package lib
Summary: lib components for the fcgi package.
Group: Libraries
Requires: fcgi-license = %{version}-%{release}

%description lib
lib components for the fcgi package.


%package license
Summary: license components for the fcgi package.
Group: Default

%description license
license components for the fcgi package.


%prep
%setup -q -n fcgi-2.4.0
cd %{_builddir}/fcgi-2.4.0
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604540862
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%reconfigure --disable-static
make

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check

%install
export SOURCE_DATE_EPOCH=1604540862
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fcgi
cp %{_builddir}/fcgi-2.4.0/LICENSE.TERMS %{buildroot}/usr/share/package-licenses/fcgi/1b868f12aa2e288540004670bbe8edfe69d3de88
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cgi-fcgi

%files dev
%defattr(-,root,root,-)
/usr/include/fastcgi.h
/usr/include/fcgi_config.h
/usr/include/fcgi_stdio.h
/usr/include/fcgiapp.h
/usr/include/fcgimisc.h
/usr/include/fcgio.h
/usr/include/fcgios.h
/usr/lib64/libfcgi++.so
/usr/lib64/libfcgi.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfcgi++.so.0
/usr/lib64/libfcgi++.so.0.0.0
/usr/lib64/libfcgi.so.0
/usr/lib64/libfcgi.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fcgi/1b868f12aa2e288540004670bbe8edfe69d3de88
