#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fcgi
Version  : 2.4.0
Release  : 4
URL      : http://fastcgi.com/dist/fcgi-2.4.0.tar.gz
Source0  : http://fastcgi.com/dist/fcgi-2.4.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : OML
Requires: fcgi-bin
Requires: fcgi-lib
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
Patch1: fcgi-2.4.0-Makefile.am-CPPFLAGS.patch
Patch2: fcgi-2.4.0-configure.in.patch
Patch3: gcc44-fix-include.patch
Patch4: cve-2012-6687.patch

%description
------------------------------
See the file "LICENSE.TERMS" for information on usage and redistribution
of this file, and for a DISCLAIMER OF ALL WARRANTIES.

%package bin
Summary: bin components for the fcgi package.
Group: Binaries

%description bin
bin components for the fcgi package.


%package dev
Summary: dev components for the fcgi package.
Group: Development
Requires: fcgi-lib
Requires: fcgi-bin
Provides: fcgi-devel

%description dev
dev components for the fcgi package.


%package lib
Summary: lib components for the fcgi package.
Group: Libraries

%description lib
lib components for the fcgi package.


%prep
%setup -q -n fcgi-2.4.0
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
%reconfigure --disable-static
make V=1

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cgi-fcgi

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
